---
- name: Copy docker compose stack files
  hosts: ["digitalocean"]
  gather_facts: no
  become: true
  vars:
    stack_name: microservices-demo
    stack_dir: /srv/microservices_demo
    docker_group: docker
    copy_to_remote_host: ["certs", ".apache", ".elastic", ".java-api", ".mongo-express", ".nodejs"]
    docker_image_name:
      - { dir: ".apache", name: "apache-php-app" }
      - { dir: ".java-api", name: "java-api" }
      - { dir: ".nodejs", name: "node-app" }

  tasks:
    - debug: var=stack_dir

    - name: Create a directory for stack
      file:
        path: "{{ stack_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ docker_group }}"
        mode: '0755'

    - name: Copy to remote host
      copy:
        src: "../{{ item }}"
        dest: "{{ stack_dir }}"
        owner: "{{ ansible_user }}"
        group: "{{ docker_group }}"
        #mode: '0644'
      with_items: "{{ copy_to_remote_host }}"

    - name: Change filebeat.yml ownership
      file:
        path: "{{ stack_dir }}/.elastic/filebeat.yml"
        owner: root
        group: root